-- PADEL ARENA MANAGER 8.0 - DATABASE COMPLETO E NON DISTRUTTIVO
-- Incollare tutto in Supabase > SQL Editor > New query > Run.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 email text, role text not null default 'collaborator', display_name text, created_at timestamptz default now(), updated_at timestamptz default now()
);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin
 insert into public.profiles(id,email,role,display_name) values(new.id,new.email,case when lower(new.email)='padelarenareggioemilia@gmail.com' then 'admin' else 'collaborator' end,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1))) on conflict(id) do update set email=excluded.email; return new; end$$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert or update of email on auth.users for each row execute function public.handle_new_user();
insert into public.profiles(id,email,role,display_name) select id,email,case when lower(email)='padelarenareggioemilia@gmail.com' then 'admin' else 'collaborator' end,coalesce(raw_user_meta_data->>'display_name',split_part(email,'@',1)) from auth.users on conflict(id) do update set email=excluded.email,role=case when lower(excluded.email)='padelarenareggioemilia@gmail.com' then 'admin' else public.profiles.role end;

create table if not exists public.players(id text primary key,data jsonb not null default '{}'::jsonb,photo_url text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.tournaments(id text primary key,name text,event_date date,club text,category text,competition_type text,logo_url text,share_token text unique not null default gen_random_uuid()::text,status text not null default 'published',data jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now());
-- Migrazione sicura di share_token: compatibile sia con vecchie colonne UUID sia con colonne TEXT.
alter table public.tournaments add column if not exists share_token text;
do $$
declare current_type text;
begin
 select data_type into current_type
 from information_schema.columns
 where table_schema='public' and table_name='tournaments' and column_name='share_token';

 if current_type is distinct from 'text' then
  alter table public.tournaments alter column share_token drop default;
  alter table public.tournaments alter column share_token type text using share_token::text;
 end if;
end$$;
alter table public.tournaments alter column share_token set default gen_random_uuid()::text;
update public.tournaments
set share_token=gen_random_uuid()::text
where share_token is null or btrim(share_token)='';
alter table public.tournaments alter column share_token set not null;
do $$declare c record;begin for c in select conname from pg_constraint where conrelid='public.tournaments'::regclass and contype='c' loop execute format('alter table public.tournaments drop constraint %I',c.conname);end loop;end$$;
alter table public.tournaments add constraint tournaments_status_check check(status in('draft','published','active','registration_open','registration_closed','completed','archived','cancelled'));
create unique index if not exists tournaments_share_token_uidx on public.tournaments(share_token);

create table if not exists public.public_registrations(id text primary key default gen_random_uuid()::text,tournament_id text not null references public.tournaments(id) on delete cascade,mode text not null check(mode in('single','pair')),primary_payload jsonb not null,partner_payload jsonb,primary_player_id text references public.players(id),partner_player_id text references public.players(id),status text not null default 'new' check(status in('new','accepted','rejected','waitlist','imported')),created_at timestamptz default now(),updated_at timestamptz default now());

create table if not exists public.championship_teams(
 id text primary key, team_name text not null, series text, club_legal_name text, club_tax_id text, club_address text, club_postal_code text, club_town text, club_province text, club_phone text, club_email text, home_court_address text, home_day text, home_time text, captain_name text, captain_email text, captain_phone text, captain_birth_date date, captain_birth_place text, captain_residence text, invite_token text unique not null, player_invite_token text unique not null, access_enabled boolean default false, roster_open boolean default true, player_self_registration_enabled boolean default true, team_logo_url text, created_at timestamptz default now(), updated_at timestamptz default now()
);
alter table public.championship_teams add column if not exists team_name text;
alter table public.championship_teams add column if not exists series text;
alter table public.championship_teams add column if not exists club_legal_name text;
alter table public.championship_teams add column if not exists club_tax_id text;
alter table public.championship_teams add column if not exists club_address text;
alter table public.championship_teams add column if not exists club_postal_code text;
alter table public.championship_teams add column if not exists club_town text;
alter table public.championship_teams add column if not exists club_province text;
alter table public.championship_teams add column if not exists club_phone text;
alter table public.championship_teams add column if not exists club_email text;
alter table public.championship_teams add column if not exists home_court_address text;
alter table public.championship_teams add column if not exists home_day text;
alter table public.championship_teams add column if not exists home_time text;
alter table public.championship_teams add column if not exists captain_name text;
alter table public.championship_teams add column if not exists captain_email text;
alter table public.championship_teams add column if not exists captain_phone text;
alter table public.championship_teams add column if not exists captain_birth_date date;
alter table public.championship_teams add column if not exists captain_birth_place text;
alter table public.championship_teams add column if not exists captain_residence text;
alter table public.championship_teams add column if not exists invite_token text;
alter table public.championship_teams add column if not exists player_invite_token text;
alter table public.championship_teams add column if not exists access_enabled boolean default false;
alter table public.championship_teams add column if not exists roster_open boolean default true;
alter table public.championship_teams add column if not exists player_self_registration_enabled boolean default true;
alter table public.championship_teams add column if not exists team_logo_url text;
alter table public.championship_teams add column if not exists updated_at timestamptz default now();
create unique index if not exists championship_teams_invite_uidx on public.championship_teams(invite_token);
create unique index if not exists championship_teams_player_invite_uidx on public.championship_teams(player_invite_token);
create table if not exists public.captain_team_access(user_id uuid references auth.users(id) on delete cascade,team_id text references public.championship_teams(id) on delete cascade,created_at timestamptz default now(),primary key(user_id,team_id));
create table if not exists public.championship_roster_players(
 id uuid primary key default gen_random_uuid(), team_id text not null references public.championship_teams(id) on delete cascade, first_name text not null,last_name text not null,birth_date date not null,birth_place text not null,postal_code text not null,residence_town text not null,residence_province text not null,phone text not null,email text not null,gender text,level text,notes text,photo_data text,status text not null default 'pending' check(status in('pending','approved','rejected')),decision_reason text,submitted_by uuid,created_at timestamptz default now(),updated_at timestamptz default now(),unique(team_id,email)
);

-- squadre ufficiali già importate
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_01','FIFTEEN RACQUET CLUB','Serie B','FIFTEEN RACQUET CLUB','03127460347','VIA RENZO PEZZANI 47A','43029','TRAVERSETOLO','PARMA','3488204373','nicola77.fagetti@gmail.com','VIA RENZO PEZZANI 47 43029 TRAVERSETOLO (PR)','Domenica','14:00 SOLO SABATO E DOMENICA','GOFFREDO GATTI','goffredo.gatti@gmail.com','334/6260938','1969-07-02','PARMA','SAN POLO D''ENZA','eb641f337adbd7e419b29c653e1d3b2b','eb641f337adbd7e419b29c653e1d3b2bplayer',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_02','CA''MARTA squadra A','Serie B','Ca''Marta sport&fun ssd a rl','03384630368','via Regina Pacis 118','41049','Ssasuolo','modena','0536812923','tommyvale99@gmail.com','Sassuolo Via Regina Pacis 118 (mo)','Sabato','14:00 SOLO SABATO E DOMENICA','Dignatici Luca','lucadignatici@hotmail.com','3357536953','1973-11-18','Sassuolo','Sassuolo','1e5c655dd0b65dae1543cb557e1c1f5d','1e5c655dd0b65dae1543cb557e1c1f5dplayer',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_03','CA''MARTA squadra B','Serie C','CA''MARTA SPORT&FUN SSD A RL UNI','03384630368','VIA REGINA PACIS 118','41049','SASSUOLO','MODENA','0536 812923','tommyvale99@gmail.com','SASSUOLO VIA REGINA PACIS 118 (mo)','Sabato','14:00 SOLO SABATO E DOMENICA','VALENTI TOMMASO','tommyvale99@gmail.com','3426480454','1989-09-21','CARPI','CARPI','f82739604639840f3993414517315476','f82739604639840f3993414517315476player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_04','CA''MARTA squadra C','Serie C','Ca''Marta sport&fun ssd a rl uni','03384630368','Regina Pacis 118','41049','Sassuolo','MODENA','0536812923','tommyvale99@gmail.com','SASSUOLO VIA REGINA PACIS 118 (MO)','Sabato','16:00 SOLO SABATO E DOMENICA','CANALI MATTEO','mcanali83@gmail.com','3282280304','1983-11-17','Sassuolo','Prignano s/s (MO)','27a2f7521b705337255ac794e591d916','27a2f7521b705337255ac794e591d916player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_05','Pol Nonantola Padel','Serie C','Polisportiva Nonantola A.D.','80015050364','Via Mazzini 34','41015','Nonantola','Modena','3479565881','polnonantola.padel@gmail.com','Via Risorgimento 50, 41015 Nonantola','Venerdi','20:00 SOLO VENERDÌ','Marco Meschiari','marco.meschiari81@gmail.com','3479565881','1981-09-15','Modena','Modena','9548bac08b29fc4b5b25f2cdced44122','9548bac08b29fc4b5b25f2cdced44122player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_06','Padel Prime La Patria Carpi','Serie C','S.G.La Patria 1879 ASD','90003660363','Via Nuova Ponente 24/H','41012','Carpi','Modena','059644070','amministrazione.lapatria@gmail.com','Via Nuova Ponente 24/H, 41012, Carpi (MO)','Sabato','14:00 SOLO SABATO E DOMENICA','Marco Gradellini','marco.grade@gmail.com','3467192364','1993-01-05','Carpi','Carpi','8968637df0729fb0ca7daa67ed41cf26','8968637df0729fb0ca7daa67ed41cf26player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_07','CT CORREGGIO 2','Serie B','Circolo Tennis Correggio ASD','91010210358','via Bruto Terrachini 2','42015','Correggio','Reggio Emilia','0522637164','direzione@ctcorreggio.it','via Bruto Terrachini 2 - 42015 Correggio (RE)','Sabato','14:00 SOLO SABATO E DOMENICA','Maurizio Musso','elemaeri@alice.it','3470887572','1972-07-11','Asti','Correggio','be07b2c3818295a3b08cdbf40536a6da','be07b2c3818295a3b08cdbf40536a6daplayer',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_08','Phoenix Cavriago','Serie B','ASD Phoenix Cavriago','02500230350','Via Torre n.3','42025','Cavriago','REGGIO NELL''EMILIA','3478979048','rocchi.marco@ognibene.com','Via Cantonazzo n.1, Cavriago 42025','Sabato','16:00 SOLO SABATO E DOMENICA','Zecchetti Patrick','patrickz@libero.it','3498945499','1990-09-07','Montecchio Emilia','Cavriago (RE) - 42025','ef291d90603a3e6407cd3b444ee7f38d','ef291d90603a3e6407cd3b444ee7f38dplayer',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_09','MIRAPADEL CENTER','Serie C','MIRAPADEL CENTER','04023790365','VIA 2 GIUGNO 26','41037','MIRANDOLA','MODENA','3428340667','info@mirapadelcenter.it','VIA 2 GIUGNO 26, 41037 MIRANDOLA (MO)','Domenica','15:00 SOLO SABATO E DOMENICA','LAGONEGRO ROSARIO','info@mirapadelcenter.it','3406686972','1976-11-15','MILANO','MIRANDOLA','be928a8283eba98180f5c62164f1e838','be928a8283eba98180f5c62164f1e838player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_10','CT CORREGGIO Serie A','Serie A','CIRCOLO TENNIS CORREGGIO ASD','91010210358','B.TERRACHINI 2','42015','CORREGGIO','REGGIO EMILIA','0522 637164','ctcorreggio@wansport.com','Via B. Terrachini 2, 42015 Correggio RE','Sabato','17:00 SOLO SABATO E DOMENICA','VEZZADINI DAVIDE','vezzadini77@gmail.com','334 6886932','1977-02-23','CORREGGIO','CORREGGIO','7d425b9a7e5fb27b622f0d6d734622bc','7d425b9a7e5fb27b622f0d6d734622bcplayer',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_11','VILLAGE PADDLE MODENA','Serie B','MODENA PADDLE CLUB SSDRL','03834490363','STRADA BELLARIA 127/1','41126','MODENA','MODENA','3512209713','tornei.villagepaddle@gmail.com','STRADA CAVEZZO 27,  41126 BAGGIOVARA (MO)','Domenica','15:00 SOLO SABATO E DOMENICA','ENZO ZARA','enzo.zara83@gmail.com','3397039671','1983-03-21','FORMIGINE (MO)','FORMIGINE (MO)','197e17dbebc13cffca9f3e02098ba27b','197e17dbebc13cffca9f3e02098ba27bplayer',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_12','B&B TEAM - Bope & Bullet','Serie A + Serie B','PADEL ARENA SRL','02906640343','Via Ernesto Ghirarduzzi 2','43122','PARMA','PARMA','+393534253475','proparmapadelarena@gmail.com','PRO GREEN STR. MARTINELLA 328 VIGATTO 43124 PR','Sabato','14:00 SOLO SABATO E DOMENICA','NICOLA GROSSI','nicolagrossi659@gmail.com','3357443152','1965-07-24','PARMA','PARMA','7ef1717ead2c959510ca1ad361968d7f','7ef1717ead2c959510ca1ad361968d7fplayer',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_13','PRO PARMA LOBOS','Serie B','PADEL ACCADEMY SSDRL','02913830341','Via Ernesto Ghirarduzzi 2','43122','Parma','Parma','3534253475','proparmapadelarena@gmail.com','Via Ernesto Ghirarduzzi 2 (Parma) cap 43122','Venerdi','20:00 SOLO VENERDÌ','Davide Chierici','crociato68@gmail.com','3313534301','1968-02-18','Parma','Montechiarugolo','b7181140951230695d6ea142595d9c7b','b7181140951230695d6ea142595d9c7bplayer',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_14','PRO PARMA TIGERS','Serie B','PADEL ACADEMY SSDRL','02913830341','ERNESTO GHIRARDUZZI, 2','43122','PARMA','PARMA','0521772686','proparmapadelarena@gmail.com','PARMA, VIA ERNESTO GHIRARDUZZI, 2 43122','Sabato','14:00 SOLO SABATO E DOMENICA','FABRIZIO VENTURINI','disossoventurini@gmail.com','3382666694','1972-09-29','PARMA','PARMA','22220d9daa1a9bf4d66f92cb0038487a','22220d9daa1a9bf4d66f92cb0038487aplayer',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_15','Punto G Nera','Serie B','ASD Punto G Padel','00702500349','Via Sonnino 21','43126','Parma','Parma','342 166 7082','segreteria@puntopadel.it','Via Sonnino 21 - 43126 Parma','Venerdi','20:00 SOLO VENERDÌ','Massimo Bosi','mbosilavoro@gmail.com','3356690914','1969-10-31','Parma','Parma','482fc05e38f16e30b19346ad48f00e21','482fc05e38f16e30b19346ad48f00e21player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_16','Punto G White','Serie B','ASD Punto G Padel','00702500349','Via Sonnino 21','43126','Parma','Parma','342 166 7082','segreteria@puntopadel.it','Via Sonnino 21 - 43126 Parma','Venerdi','20:00 SOLO VENERDÌ','Francesco Pizzi','francescopizzi80@gmail.com','3483616933','1980-02-18','San Secondo Parmense','Roccabianca','8e6e3ccf4f94c517c0ac869c1fbfe4c7','8e6e3ccf4f94c517c0ac869c1fbfe4c7player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_17','CANI SCIOLTI','Serie C','PADEL CLUB REGGIOLO SRLSD','02949130351','Strada Gavello n.3','42046','Reggiolo','Reggio Emilia','3287469448','info@padelclubreggiolo.com','Strada Gavello n.3, Reggiolo (RE) 42046','Domenica','11:00 SOLO DOMENICA','Gabriele Palmieri','gpalmieri@ag-informatica.com','3481520720','1968-05-24','Campagnola Emilia','Campagnola Emilia','9860922d476ad5fcefd8f2ba49ceb75d','9860922d476ad5fcefd8f2ba49ceb75dplayer',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_18','PALA RBG CREW','Serie C','RACQUET BALL GAMES SSDaRL','03121830354','VIA DEI PRATONIERI 7','42124','REGGIO EMILIA','REGGIO EMILIA','3275612828','racquetball@tim.it','VIA ERNESTO SPALLANZANI 8/A - 42124','Domenica','17:00 SOLO SABATO E DOMENICA','RINALDI MARCO','ing.rinaldi.marco@gmail.com','3337188334','1980-11-20','FORMIGINE (MO)','REGGIO EMILIA','a4fe0e70c3a61f4ccdef016ea48943f1','a4fe0e70c3a61f4ccdef016ea48943f1player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_19','PLAYA PADEL','Serie B + Serie C','PLAYA ASD','90054040366','VIA IMPERIALE 22/A','41037','MIRANDOLA','MODENA','3382130665','measportsrl@gmail.com','Via imperiale 22/a 41037 Mirandola (MO)','Domenica','10:00 SOLO DOMENICA','FAGLIONI ENRICO','enricofaglioni70@gmail.com','3382130665','1970-09-14','MIRANDOLA (MO)','CAVEZZO (MO)','7357a7a2dcc1b11c0ea6f3b6a4d7a8cc','7357a7a2dcc1b11c0ea6f3b6a4d7a8ccplayer',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_20','ALL STAR PADEL -SERIE C','Serie C','ALL STAR PADEL SSDRL','04028950360','VIA LAVACCHI 1635','41038','SAN FELICE SUL PANARO','MODENA','3395796474','amministrazione.allstarpadel@gmail.com','VIA LAVACCHI 1635, 41038 SAN FELICE SUL PANARO','Sabato','17:00 SOLO SABATO E DOMENICA','ENRICO LEONELLI','enrico.allstarpadel@gmail.com','3403669735','1979-01-21','BONDENO','BONDENO','bd25d724f413b7895c5b251ad38d20a6','bd25d724f413b7895c5b251ad38d20a6player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_21','La quercia B','Serie B','Ssd','02671840201','Stradello Opi 7','46026','Suzzara','Mantova','3498698003','laquerciapadel@gmail.it','Stradello Opi 7 46029 suzzara','Sabato','15:00 SOLO SABATO E DOMENICA','Stefano Storchi','stefano_storchi@virgilio.it','3358433367','2026-07-30','Suzzara','Suzzara','321e31ec5dcc9ef11bd229e1effc4822','321e31ec5dcc9ef11bd229e1effc4822player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_22','HORMIGA PADEL CLUB','Serie B','ASD HORMIGA','CF 94212630365','VIA PANARO 193','41056','SAVIGNANO SUL PANARO','MODENA','3240413208','hormigapadel@gmail.com','via panaro 193, Formica di Savignano sul Panaro','Domenica','11:00 SOLO DOMENICA','MAURO FIORANI','fioranimauro64@gmal.com','3358238780','1964-11-08','MODENA','MODENA','1d3ce08606b3a37d3a880a33af177711','1d3ce08606b3a37d3a880a33af177711player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_23','Quercia C','Serie C','Ssd','02671840201','Stradello Opi 7','46029','Suzzara','Mantova','3498698003','laquerciapadel@gmail.it','Stradello Opi 7 46029 suzzara','Sabato','14:00 SOLO SABATO E DOMENICA','Stefano Storchi','stefano_storchi@virgilio.it','3358433367','2026-07-14','Suzzara','Mantova','9b652470e6cae54b99aba9e12013cba2','9b652470e6cae54b99aba9e12013cba2player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_24','Padel San Donnino A','Serie C','Padel San Donnino S.S.D a R.L.','04053390367','Via della Genziana, 18','41126','Modena','Modena','3666358467','padelsandonnino@gmail.com','Via della Genziana, 18, 41126','Sabato','17:00 SOLO SABATO E DOMENICA','Francesco Teoli','francesco.teoli09@gmail.com','3472612643','2002-10-01','Modena','Modena','452df60bf8a25ddd65124021e140d479','452df60bf8a25ddd65124021e140d479player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_25','Padel San Donnino B','Serie C','Padel San Donnino S.S.D. a R.L.','04053390367','Via della Genziana 18','41126','Modena','Modena','3666358467','padelsandonnino@gmail.com','Via della Genziana 18, 41126','Domenica','15:00 SOLO SABATO E DOMENICA','Francesco Teoli','francesco.teoli09@gmail.com','3472612643','2002-10-01','Modena','Modena','68c779bcfdb353fe25005b757bc49f13','68c779bcfdb353fe25005b757bc49f13player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_26','Qui Pádel C','Serie C','Qui Padel & Fun SSD','02674970203','G. Di Vittorio 49','46026','Quistello','MN','3458345177','quipadel@gmail.com','via Allende 7, 46026 Quistello MN','Domenica','15:00 SOLO SABATO E DOMENICA','Emiliano Verolla','emilioverolla11@gmail.com','3458345177','1978-10-11','Formia LT','Carpi','26715c3fd053394ceb51c3c5579be8d8','26715c3fd053394ceb51c3c5579be8d8player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_27','EDEN ACADEMY SERIE C','Serie C','EDEN SPORT & SALUTE','02310620352','VIA G.BALLA 6','42124','REGGIO EMILIA','RE','0522944244','info@edenbenessere.it','VIA G.BALLA 6 42124 REGGIO EMILIA','Domenica','17:00 SOLO SABATO E DOMENICA','AUGUSTO AUBRY','augustoaubry@gmail.com','3405918068','1974-09-27','NAPOLI','SCANDIANO','cb5ff81c53eb60444a471cb80d6f2a27','cb5ff81c53eb60444a471cb80d6f2a27player',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_28','BLUE PADEL CARPI C','Serie C','BLUE PADEL CARPI','03955960368','PIAZZALE DELLE PISCINE 4','41012','CARPI','modena','MO','amministrazione.bluepadelcarpi@gmail.com','Piazzale delle piscine 4 carpi 41012','Sabato','15:00 SOLO SABATO E DOMENICA','Maria Pia Calabrese','pia@maglificiolsm.com','3333208040','1991-09-30','carpi','carpi','fc74338b71f7af2969764bcb46af624c','fc74338b71f7af2969764bcb46af624cplayer',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;
insert into public.championship_teams (id,team_name,series,club_legal_name,club_tax_id,club_address,club_postal_code,club_town,club_province,club_phone,club_email,home_court_address,home_day,home_time,captain_name,captain_email,captain_phone,captain_birth_date,captain_birth_place,captain_residence,invite_token,player_invite_token,access_enabled,roster_open,player_self_registration_enabled) values ('aics2027_29','BLUE PADEL CARPI B','Serie B','BLUE PADEL CARPI','03955960368','PIAZZALE DELLE PISCINE 4','41012','CARPI','MODENA','3333208040','pia@maglificiolsm.com','PIAZZALE DELLE PISCINE 4 CARPI 41012','Venerdi','20:00 SOLO VENERDÌ','MARIA PIA CALABRESE','pia@maglificiolsm.com','3333208040','1991-09-30','CARPI','CARPI','7d069a1fbf11a1d1a8a6d086ab0037fe','7d069a1fbf11a1d1a8a6d086ab0037feplayer',false,true,true) on conflict (id) do update set team_name=excluded.team_name,series=excluded.series,club_legal_name=excluded.club_legal_name,club_tax_id=excluded.club_tax_id,club_address=excluded.club_address,club_postal_code=excluded.club_postal_code,club_town=excluded.club_town,club_province=excluded.club_province,club_phone=excluded.club_phone,club_email=excluded.club_email,home_court_address=excluded.home_court_address,home_day=excluded.home_day,home_time=excluded.home_time,captain_name=excluded.captain_name,captain_email=excluded.captain_email,captain_phone=excluded.captain_phone,captain_birth_date=excluded.captain_birth_date,captain_birth_place=excluded.captain_birth_place,captain_residence=excluded.captain_residence,invite_token=excluded.invite_token,player_invite_token=excluded.player_invite_token,access_enabled=excluded.access_enabled,roster_open=excluded.roster_open,player_self_registration_enabled=excluded.player_self_registration_enabled;

-- funzioni pubbliche tornei
drop function if exists public.public_tournament_for_registration(uuid);
drop function if exists public.public_tournament_for_registration(text);
drop function if exists public.public_search_players_for_registration(uuid,text);
drop function if exists public.public_search_players_for_registration(text,text);
drop function if exists public.public_submit_tournament_registration_request(uuid,text,jsonb,jsonb);
drop function if exists public.public_submit_tournament_registration_request(text,text,jsonb,jsonb);
create or replace function public.public_tournament_for_registration(p_share_token text) returns jsonb language plpgsql security definer set search_path=public as $$declare t public.tournaments; d jsonb; count_ok int;begin select * into t from public.tournaments where share_token=p_share_token limit 1;if not found then return null;end if;d=coalesce(t.data,'{}'::jsonb);select count(*) into count_ok from public.public_registrations where tournament_id=t.id and status in('accepted','imported');return jsonb_build_object('id',t.id,'name',coalesce(t.name,d->>'name'),'date',coalesce(t.event_date::text,d->>'date'),'start_time',d->>'startTime','end_date',d->>'endDate','end_time',d->>'endTime','club',coalesce(t.club,d->>'club'),'address',d->>'customAddress','category',coalesce(t.category,d->>'category'),'competition_type',coalesce(t.competition_type,d->>'competitionType'),'logo_url',coalesce(t.logo_url,d->>'logoUrl'),'description',d->>'description','entry_fee',coalesce((d->>'entryFee')::numeric,0),'max_participants',coalesce((d->>'registrationCapacity')::int,(d->>'maxParticipants')::int),'available_places',greatest(0,coalesce((d->>'registrationCapacity')::int,(d->>'maxParticipants')::int,999)-count_ok),'registration_open',coalesce((d->>'registrationOpen')::boolean,true),'poster_theme',coalesce(d->>'posterTheme','eden_summer'),'accent','#9dff25');end$$;
create or replace function public.public_search_players_for_registration(p_share_token text,p_query text) returns table(id text,full_name text) language sql security definer set search_path=public as $$select p.id,trim(coalesce(p.data->>'firstName','')||' '||coalesce(p.data->>'lastName','')) from public.players p where exists(select 1 from public.tournaments t where t.share_token=p_share_token) and lower(trim(coalesce(p.data->>'firstName','')||' '||coalesce(p.data->>'lastName',''))) like '%'||lower(trim(p_query))||'%' order by 2 limit 20$$;
create or replace function public.public_submit_tournament_registration_request(p_share_token text,p_mode text,p_primary jsonb,p_partner jsonb default null) returns jsonb language plpgsql security definer set search_path=public as $$declare tid text; rid text; cap int; accepted_count int; st text:='new';begin select id,coalesce((data->>'registrationCapacity')::int,(data->>'maxParticipants')::int) into tid,cap from public.tournaments where share_token=p_share_token and coalesce((data->>'registrationOpen')::boolean,true)=true;if tid is null then raise exception 'Iscrizioni chiuse o torneo non trovato';end if;if p_mode not in('single','pair') then raise exception 'Modalità non valida';end if;select count(*) into accepted_count from public.public_registrations where tournament_id=tid and status in('accepted','imported');if cap is not null and accepted_count>=cap then st:='waitlist';end if;insert into public.public_registrations(tournament_id,mode,primary_payload,partner_payload,status) values(tid,p_mode,p_primary,p_partner,st) returning id into rid;return jsonb_build_object('id',rid,'status',st,'message',case when st='waitlist' then 'Posti esauriti: richiesta inserita in lista d’attesa.' else 'Richiesta inviata all’organizzatore.' end);end$$;
create or replace function public.admin_process_public_registration(p_registration_id text,p_action text,p_capacity integer default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare r public.public_registrations; pp jsonb; pid1 text; pid2 text; ids jsonb;
begin
 if not exists(select 1 from public.profiles where id=auth.uid() and role='admin') then raise exception 'Operazione riservata all’amministratore'; end if;
 select * into r from public.public_registrations where id=p_registration_id for update;
 if not found then raise exception 'Richiesta non trovata'; end if;
 if p_action='accepted' then
  pp=r.primary_payload;
  if pp->>'kind'='existing' then pid1=pp->>'player_id'; else pid1='p_'||gen_random_uuid()::text; insert into public.players(id,data) values(pid1,pp->'data') on conflict(id) do update set data=excluded.data,updated_at=now(); end if;
  if r.partner_payload is not null then
   pp=r.partner_payload;
   if pp->>'kind'='existing' then pid2=pp->>'player_id'; else pid2='p_'||gen_random_uuid()::text; insert into public.players(id,data) values(pid2,pp->'data') on conflict(id) do update set data=excluded.data,updated_at=now(); end if;
  end if;
  update public.public_registrations set status='accepted',primary_player_id=pid1,partner_player_id=pid2,updated_at=now() where id=r.id;
 elsif p_action='waitlist' then update public.public_registrations set status='waitlist',updated_at=now() where id=r.id;
 elsif p_action='rejected' then update public.public_registrations set status='rejected',updated_at=now() where id=r.id;
 else raise exception 'Azione non valida'; end if;
 ids=jsonb_build_array(pid1,pid2);
 return jsonb_build_object('status',p_action,'player_ids',ids);
end$$;

-- funzioni campionato e rose
create or replace function public.public_championship_team_for_captain(p_token text) returns jsonb language sql security definer set search_path=public as $$select to_jsonb(t) from public.championship_teams t where t.invite_token=p_token and t.access_enabled=true limit 1$$;
create or replace function public.claim_championship_team_access(p_token text) returns jsonb language plpgsql security definer set search_path=public as $$declare t public.championship_teams; em text;begin if auth.uid() is null then raise exception 'Accedi prima di continuare';end if;select email into em from auth.users where id=auth.uid();select * into t from public.championship_teams where invite_token=p_token and access_enabled=true limit 1;if not found then raise exception 'Accesso non abilitato';end if;if lower(coalesce(em,''))<>lower(coalesce(t.captain_email,'')) then raise exception 'Usa l’email del capitano registrata per questa squadra';end if;insert into public.captain_team_access(user_id,team_id) values(auth.uid(),t.id) on conflict do nothing;return to_jsonb(t);end$$;
create or replace function public.public_championship_team_for_roster(p_token text) returns jsonb language sql security definer set search_path=public as $$select jsonb_build_object('id',t.id,'team_name',t.team_name,'series',t.series,'club_legal_name',t.club_legal_name,'team_logo_url',t.team_logo_url,'roster_open',t.roster_open) from public.championship_teams t where t.player_invite_token=p_token and t.roster_open=true and t.player_self_registration_enabled=true limit 1$$;
create or replace function public.public_submit_championship_roster_player(p_token text,p_payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$declare tid text; rid uuid;begin select id into tid from public.championship_teams where player_invite_token=p_token and roster_open=true and player_self_registration_enabled=true;if tid is null then raise exception 'Raccolta rosa chiusa o link non valido';end if;insert into public.championship_roster_players(team_id,first_name,last_name,birth_date,birth_place,postal_code,residence_town,residence_province,phone,email,gender,level,notes,photo_data,submitted_by) values(tid,p_payload->>'first_name',p_payload->>'last_name',(p_payload->>'birth_date')::date,p_payload->>'birth_place',p_payload->>'postal_code',p_payload->>'residence_town',upper(p_payload->>'residence_province'),p_payload->>'phone',lower(p_payload->>'email'),p_payload->>'gender',p_payload->>'level',p_payload->>'notes',p_payload->>'photo_data',auth.uid()) on conflict(team_id,email) do update set first_name=excluded.first_name,last_name=excluded.last_name,birth_date=excluded.birth_date,birth_place=excluded.birth_place,postal_code=excluded.postal_code,residence_town=excluded.residence_town,residence_province=excluded.residence_province,phone=excluded.phone,gender=excluded.gender,level=excluded.level,notes=excluded.notes,photo_data=excluded.photo_data,status='pending',decision_reason=null,updated_at=now() returning id into rid;return jsonb_build_object('id',rid,'message','Richiesta inviata e in attesa di approvazione.');end$$;
create or replace function public.decide_championship_roster_player(p_player_id uuid,p_decision text,p_reason text default null) returns jsonb language plpgsql security definer set search_path=public as $$declare tid text; allowed boolean;begin if p_decision not in('approved','rejected') then raise exception 'Decisione non valida';end if;select team_id into tid from public.championship_roster_players where id=p_player_id;allowed=exists(select 1 from public.profiles where id=auth.uid() and role='admin') or exists(select 1 from public.captain_team_access where user_id=auth.uid() and team_id=tid);if not allowed then raise exception 'Non autorizzato';end if;update public.championship_roster_players set status=p_decision,decision_reason=p_reason,updated_at=now() where id=p_player_id;return jsonb_build_object('status',p_decision);end$$;

-- RLS e permessi
alter table public.profiles enable row level security;alter table public.players enable row level security;alter table public.tournaments enable row level security;alter table public.public_registrations enable row level security;alter table public.championship_teams enable row level security;alter table public.captain_team_access enable row level security;alter table public.championship_roster_players enable row level security;
do $$declare r record;begin for r in select schemaname,tablename,policyname from pg_policies where schemaname='public' and tablename in('profiles','players','tournaments','public_registrations','championship_teams','captain_team_access','championship_roster_players') loop execute format('drop policy if exists %I on %I.%I',r.policyname,r.schemaname,r.tablename);end loop;end$$;
create policy profiles_own on public.profiles for select to authenticated using(id=auth.uid());
create policy players_auth on public.players for all to authenticated using(true) with check(true);
create policy tournaments_auth on public.tournaments for all to authenticated using(true) with check(true);
create policy registrations_auth on public.public_registrations for all to authenticated using(true) with check(true);
create policy teams_admin_select on public.championship_teams for select to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin') or exists(select 1 from public.captain_team_access a where a.user_id=auth.uid() and a.team_id=id));
create policy teams_admin_update on public.championship_teams for update to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin') or exists(select 1 from public.captain_team_access a where a.user_id=auth.uid() and a.team_id=id)) with check(true);
create policy access_own on public.captain_team_access for select to authenticated using(user_id=auth.uid());
create policy roster_manage on public.championship_roster_players for all to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin') or exists(select 1 from public.captain_team_access a where a.user_id=auth.uid() and a.team_id=team_id)) with check(true);
grant usage on schema public to anon,authenticated;grant select,insert,update,delete on public.players,public.tournaments,public.public_registrations,public.championship_teams,public.captain_team_access,public.championship_roster_players to authenticated;grant execute on function public.public_tournament_for_registration(text),public.public_search_players_for_registration(text,text),public.public_submit_tournament_registration_request(text,text,jsonb,jsonb),public.public_championship_team_for_captain(text),public.public_championship_team_for_roster(text),public.public_submit_championship_roster_player(text,jsonb) to anon,authenticated;grant execute on function public.admin_process_public_registration(text,text,integer),public.claim_championship_team_access(text),public.decide_championship_roster_player(uuid,text,text) to authenticated;

-- storage loghi/foto
insert into storage.buckets(id,name,public) values('padel-arena-images','padel-arena-images',true) on conflict(id) do update set public=true;
drop policy if exists images_public_read on storage.objects;create policy images_public_read on storage.objects for select to public using(bucket_id='padel-arena-images');drop policy if exists images_auth_write on storage.objects;create policy images_auth_write on storage.objects for all to authenticated using(bucket_id='padel-arena-images') with check(bucket_id='padel-arena-images');
notify pgrst,'reload schema';
